services:
  postgres:
    image: postgres:15
    container_name: faa_postgres
    environment:
      POSTGRES_USER: faa
      POSTGRES_PASSWORD: faa
      POSTGRES_DB: faa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faa"]
      interval: 5s
      retries: 5
      start_period: 5s

  api_service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: faa_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg://faa:faa@postgres:5432/faa
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: bash -c "sleep 3 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: faa_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api_service
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: streamlit run app/1_Home.py --server.address 0.0.0.0 --server.port 8501

volumes:
  postgres_data: